stages:
  - publish
  - deploy

variables:
  AWS_DEFAULT_REGION: ap-northeast-2
  APP_NAME: hey-board-game
  TAG_LATEST: $AWS_ECR_REGISTRY/$APP_NAME:latest

before_script:
  - apk add --no-cache curl jq python3 py3-pip
  - pip install awscli
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ECR_REGISTRY
  - aws --version
  - docker --version

publish:
  image: docker:24.0.4
  stage: publish
  services:
    - docker:24.0.4-dind
  script:
    - docker build -t $TAG_LATEST .
    - aws ecr batch-delete-image
      --repository-name $APP_NAME
      --image-ids imageTag=latest
    - docker push $TAG_LATEST
  only:
    - develop
    - main

deploy:
  image: docker:24.0.4
  stage: deploy
  services:
    - docker:24.0.4-dind
  script:
    - aws lambda update-function-code
      --function-name hey-board-game-lambda
      --image-uri $TAG_LATEST
  only:
    - main